export const GET_CONVERSATIONS = "GET_CONVERSATIONS";
export const CREATE_CONVERSATION = "CREATE_CONVERSATION";
export const SELECT_CONVERSATION = "SELECT_CONVERSATION";
export const GET_MESSAGES = "GET_MESSAGES"
